FROM rstmpw/php74:7.4.29

RUN set -ex \
		&& apt-get clean && apt-get update \
		# install cron
		&& apt-get install -y --no-install-recommends cron && which cron \
    	&& apt-get autoclean -qy && rm -rf /var/lib/apt/lists/* \
    	#&& mkfifo --mode 0666 /var/log/cron.log \
    	&& rm -rf /etc/cron.*/* \
    	&& mkdir -p /opt/crontabs

VOLUME ["/opt/crontabs"]

COPY entrypoint-debian.sh /usr/sbin/entrypoint.sh

ENTRYPOINT ["entrypoint.sh"]

CMD ["cron", "-f", "-L", "2"]