version: '3'

services:
  php71:
    image: rstmpw/php71
    build:
      context: ./php71
#    volumes:
#      - ./php71/pool.dist.conf:/usr/local/etc/php-fpm.d/www.conf:ro
#      - ./php71/php-fpm.dist.conf:/usr/local/etc/php-fpm.conf:ro

  php71mqseries:
    image: rstmpw/php71mqseries
    build:
      context: ./php71mqseries
#    volumes:
#      - ./php71/pool.dist.conf:/usr/local/etc/php-fpm.d/www.conf:ro
#      - ./php71/php-fpm.dist.conf:/usr/local/etc/php-fpm.conf:ro
    depends_on:
      - php71

  nginx:
    image: rstmpw/nginx
    build:
      context: ./nginx
    ports:
      - 80:80
      - 443:443
#    volumes:
#      - ./nginx/vhost.default.conf:/etc/nginx/conf.d/default.conf:ro
#      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro

  pgsql96:
    image: rstmpw/pgsql96
    build:
      context: ./pgsql96
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: vagrant
      POSTGRES_INITDB_ARGS: "--lc-collate=C --lc-ctype=ru_RU.UTF-8 --lc-messages=en_US.UTF-8 --encoding=UTF-8"
    volumes:
      - ./pgsql96/initdb.sql:/docker-entrypoint-initdb.d/init.sql:ro
#      - ./pgsq96/override.conf:/etc/pgsql/conf.d/10-override.conf:ro
#      - ./pgsql96/data/:/var/lib/postgresql/data

  dnsmasq:
    image: rstmpw/dnsmasq
    build:
      context: ./dnsmasq
    ports:
      - "53:53/udp"
      - "53:53/tcp"
    cap_add:
      - NET_ADMIN
    volumes:
      - ./dnsmasq/dns.conf:/etc/dnsmasq.d/override.conf:ro
      - ./dnsmasq/addn-hosts:/etc/dnsmasq.d/addn-hosts:ro

  rabbitmq:
    image: rstmpw/rabbitmq
    build:
      context: ./rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    hostname: tr-1-50
    environment:
      RABBITMQ_DEFAULT_USER: 'root'
      RABBITMQ_DEFAULT_PASS: 'Secret'
      RABBITMQ_DEFAULT_VHOST: '/'
#      RABBITMQ_HIPE_COMPILE: 1
#    volumes:
#      - ./data:/var/lib/rabbitmq
#      - ./etc/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro
#      - ./definitions.json:/etc/rabbitmq/definitions.json:ro # no shovels here